#!/bin/bash
# Get the comma separated output for the testing summary spreadsheet.
# Columns:
#		Name:	CPUSuite
#		Day:	Date of qb_run.out file
#		Run:	Always "1"
#		Score:	Taken from "CPU Score" line of CPURun output.
#
echo "CPUSuite, $(stat -c %y $1/qb_run.out | cut -d" " -f1), 1, $(cat $1/qb_run.out | grep "CPU Score" | cut -d" " -f4)"
