<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Grappa: high-throughput graph processing on mass-market clusters</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Home page of Grappa project at UW CSE">
    <meta name="author" content="Jacob Nelson">

    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }

      .orange {
      color: orange;
      }

      .hero-img {
	background-image: url("images/hairball-header-cropped.jpg");
	background-position:top right;
	background-repeat:no-repeat;
	z-index:1;
      }
    </style>
    
    <!-- work on smaller screens -->
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    
