#!/bin/bash
DIR="${BASH_SOURCE%/*}"

# setup data container with grappa source in volume '/grappa'
# - pulls the grappa-base repository from the registry
docker run --name grappa-container -v /grappa uwsampa/grappa-base

# share /grappa with host via Samba
# - to connect to it, use `boot2docker ip` to get the IP address of the VM and do "Finder > Connect to Server..." and connect via: cifs://`boot2docker ip 2>`/grappa
docker run --rm -v /usr/local/bin/docker:/docker -v /var/run/docker.sock:/docker.sock svendowideit/samba grappa-container

# then to run bash in a grappa environment, with this editable source code, do:
# > docker run -ti --volumes-from=grappa-container uwsampa/grappa-base
# or for a fresh environment:
# > docker run -ti uwsampa/grappa-base

# TODO: separate out 'uwsampa/grappa' to be the one with the VOLUME and latest grappa source, and have 'uwsampa/grappa-base' only have /grappa-third-party
