#!/bin/bash
##############################################################
# Launch a shell in a Grappa container using data containers
##############################################################
DIR="${BASH_SOURCE%/*}"
source $DIR/../util/common.sh
init_flags

DEFINE_string 'src' 'grappa-src' 'Container providing source files in /grappa' 's'
DEFINE_string 'build' 'grappa-build' 'Container providing build directory at /build' 'b'

# parse the command-line
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

docker run --volumes-from=$FLAGS_src --volumes-from=$FLAGS_build -ti --privileged uwsampa/grappa
