#
# copyright 2009 Convey Computer Corp.
#

OLD=1

ifeq ($(OLD),1)

include ./Makefile.old

else

####################################################################
# Include Convey Makefile Template
####################################################################
include $(CNY_PDK)/$(CNY_PDK_REV)/lib/MakefileInclude.cnypdk

endif
