#define GRAPPA_COMM_GROUP profile_groups[0]
#define GRAPPA_LATENCY_GROUP profile_groups[1]
#define GRAPPA_USER_GROUP profile_groups[2]
#define GRAPPA_USERAM_GROUP profile_groups[3]
#define GRAPPA_SCHEDULER_GROUP profile_groups[4]
#define GRAPPA_SUSPEND_GROUP profile_groups[5]
#define GRAPPA_TASK_GROUP profile_groups[6]
#define GRAPPA_STATE_TIMER_GROUP profile_groups[7]
