# Makefile $Header: /cvs/cae_vadd/sim/Makefile,v 1.16 2010/12/01 12:34:57 gedwards Exp $

# To compile additional verilog modules for simulation:
# CNY_PDK_TB_USER_VLOG += tb_user.v

# To fix the seed for simulation:
# CNY_PDK_SIM_SEED = 11223344

####################################################################
# Include Convey Makefile Template
####################################################################
include ../Makefile.include

SILENT ?= .SILENT   # Allow Override of Silent

$(SILENT):

CNY_PDK_SIM_CLEAN_LIST += 

