# Makefile $Header: /cvs/cae_vadd_mxb/phys/Makefile,v 1.3 2010/10/17 16:15:42 gedwards Exp $

#UCF_FILES += smpl_pers.ucf
#UCF_FILES += comp_xbar.ucf

####################################################################
# Include Convey Makefile Template
####################################################################
include $(CNY_PDK)/$(CNY_PDK_REV)/lib/MakefileInclude.cnypdk

