CC = /data/sea/cascade/build/GOODNIGHT/linux/mta/cobra/bin/cc
LD = /data/sea/cascade/build/GOODNIGHT/linux/mta/cobra/bin/cc

small:
	$(CC) -par -o main -DSMALL_PROBLEM main.c init.c conn_jgl.c -lm -lprand

clean:
	/bin/rm *.o *.pl
