# Makefile $Header: /cvs/cae_vadd/phys/Makefile,v 1.6 2010/12/15 20:27:48 gedwards Exp $

####################################################################
# Include Convey Makefile Template
####################################################################
include ../Makefile.include

SILENT ?= .SILENT   # Allow Override of Silent

$(SILENT):
